### ISSUE TITLE
Redirections / HTTP Codes controllers tests

### ISSUE THREAD

**Issue by Tom-Bonnike** [baloran/tilter#15]
(GET routes only TODO)

- TweetsController
  - the homepage (index action) should require authentification (devise), and redirect to sign in page if not logged in, 200 if logged in.
  - accessing the homepage at `/tilts` should redirect to `/` with a 301 if logged in
  - trying to access a single tweet should require authentification (devise), return a 401 and redirect to sign in page if not logged in, 200 if logged in and exists
  - get on a non existing tweet id should return a 404 (and show 404 page)

<br>

- UsersController
  - all routes should require authentification (devise), return 401s and redirect to sign in page if not logged in, 200 if logged in
  - get on a non existing user id should return a 404 (and show 404 page)

**Comment by baloran** [comment]
not fix

**Comment by Tom-Bonnike** [comment]
thx
<img src="https://media1.tenor.com/images/5fe0a08b87dfbe419d39d0a507685d26/tenor.gif?itemid=10574413">
